# Generated by Django 6.0.2 on 2026-06-02 03:26

import django.core.validators
from django.db import migrations, models


def backfill_stock_effect(apps, schema_editor):
    """Заполняет stock_effect для уже существующих операций.

    Для прихода эффект равен +количество, для расхода и списания — −количество.
    Для корректировки прежнее количество неизвестно, поэтому эффект остаётся 0.
    """
    Transaction = apps.get_model('inventory', 'Transaction')
    for t in Transaction.objects.all():
        if t.transaction_type == 'in':
            t.stock_effect = t.quantity
        elif t.transaction_type in ('out', 'write_off'):
            t.stock_effect = -t.quantity
        else:
            t.stock_effect = 0
        t.save(update_fields=['stock_effect'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stock_effect',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Служебное поле: фактическое изменение остатка этой операцией (для корректного отката)', max_digits=10, verbose_name='Изменение остатка'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.RunPython(backfill_stock_effect, migrations.RunPython.noop),
    ]
