# Generated by Django 6.0.2 on 2026-06-02 04:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transaction_stock_effect_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_movements',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Служебное поле: какие партии и на сколько изменила операция (для отката)', verbose_name='Движение партий'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Только для прихода медикамента', null=True, verbose_name='Срок годности партии'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Только для прихода медикамента: создаётся партия с этим лотом', max_length=100, verbose_name='Номер партии (лот)'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Номер партии (лот)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поступило')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток партии')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена закупки за единицу')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.medication', verbose_name='Медикамент')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True), 'received_at', 'id'],
            },
        ),
    ]
