# Generated by Django 6.0.2 on 2026-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_opening_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablematerial',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
    ]
